<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.browserstack</groupId>
    <artifactId>testng-browserstack</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>testng-browserstack</name>
    <url>https://www.github.com/browserstack/testng-browserstack</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <testng.version>7.4.0</testng.version>
        <surefire.version>2.19.1</surefire.version>
        <selenium.version>4.13.0</selenium.version>
        <json-simple.version>1.1.1</json-simple.version>
        <config.file>config/sample-test.testng.xml</config.file>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.13.0</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.browserstack</groupId>
            <artifactId>browserstack-java-sdk</artifactId>
            <version>LATEST</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>getClasspathFilenames</id>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>${config.file}</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>sample-local-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-local-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-percy-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-percy-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>retry</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/retry.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-local-execution-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-local-execution-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-failed-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-failed-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-class-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-class-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-assertion-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-assertion-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-api-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-api-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-a11y-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-a11y-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-stability</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-stability.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>morecommand</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/performance.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>annotation</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/annotation.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>retry-analyzer</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/retry-analyzer.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>dependency-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/dependency-test-testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

         <profile>
            <id>parallel</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.2</version>
                        <configuration>
                            <parallel>suites</parallel>
                            <threadCount>2</threadCount>
                                <suiteXmlFiles>
									<suiteXmlFile>config/sample-test.testng.xml</suiteXmlFile>
									<suiteXmlFile>config/sample-local-test.testng.xml</suiteXmlFile>
								</suiteXmlFiles>
							<argLine>
								-javaagent:${com.browserstack:browserstack-java-sdk:jar}
							</argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

         <profile>
            <id>sample-nppp-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.2</version>
                        <configuration>
                                <suiteXmlFiles>
									<suiteXmlFile>config/sample-nppp.testng.xml</suiteXmlFile>
								</suiteXmlFiles>
							<argLine>
								-javaagent:${com.browserstack:browserstack-java-sdk:jar}
							</argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-self-healing-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.2</version>
                        <configuration>
                                <suiteXmlFiles>
									<suiteXmlFile>config/sample-self-healing.testng.xml</suiteXmlFile>
								</suiteXmlFiles>
							<argLine>
								-javaagent:${com.browserstack:browserstack-java-sdk:jar}
							</argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        
        <profile>
            <id>sample-upload-media-tags-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.2</version>
                        <configuration>
                                <suiteXmlFiles>
									<suiteXmlFile>config/sample-upload-media.testng.xml</suiteXmlFile>
								</suiteXmlFiles>
							<argLine>
								-javaagent:${com.browserstack:browserstack-java-sdk:jar}
							</argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>individual-test-tags</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.5.2</version>
                        <configuration>
                                <suiteXmlFiles>
									<suiteXmlFile>config/individual-test-tags.testng.xml</suiteXmlFile>
								</suiteXmlFiles>
							<argLine>
								-javaagent:${com.browserstack:browserstack-java-sdk:jar}
							</argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-maximized-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-maximized-test.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>non-infra-cbt</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/non-infra-cbt.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>session-linking-offthread</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/session-linking-offthread.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sample-legacy-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-legacy-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>smart-selection</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <suiteXmlFiles>
                                <suiteXmlFile>config/sample-sts-test.testng.xml</suiteXmlFile>
                            </suiteXmlFiles>
                            <argLine>
                                -javaagent:${com.browserstack:browserstack-java-sdk:jar}
                            </argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>
</project>
